exports.up = pgm => {
    pgm.sql(`
    CREATE TABLE type (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(20) NOT NULL
    );

    CREATE TABLE elem (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type_id INTEGER NOT NULL,
      name VARCHAR(50) NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      win_count INTEGER NOT NULL DEFAULT 0,
      CONSTRAINT elem_fk_type_id FOREIGN KEY (type_id) REFERENCES type(id)
    );

    CREATE TABLE selected_elem (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      elem_id INTEGER NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      CONSTRAINT selected_elem_fk_elem_id FOREIGN KEY (elem_id) REFERENCES elem(id)
    );

    CREATE TABLE unselected_elem (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      selected_elem_id INTEGER NOT NULL,
      elem_id INTEGER NOT NULL,
      created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
      CONSTRAINT unselected_elem_fk_selected_elem_id
        FOREIGN KEY (selected_elem_id) REFERENCES selected_elem(id),
      CONSTRAINT unselected_elem_fk_elem_id
        FOREIGN KEY (elem_id) REFERENCES elem(id)
    );

    CREATE INDEX idx_elem_type_id ON elem(type_id);
    CREATE INDEX idx_selected_elem_elem_id ON selected_elem(elem_id);
    CREATE INDEX idx_unselected_elem_selected_elem_id ON unselected_elem(selected_elem_id);
    CREATE INDEX idx_unselected_elem_elem_id ON unselected_elem(elem_id);
  `)
}

exports.down = pgm => {
    pgm.sql(`
    DROP TABLE IF EXISTS unselected_elem;
    DROP TABLE IF EXISTS selected_elem;
    DROP TABLE IF EXISTS elem;
    DROP TABLE IF EXISTS type;
  `)
}
