module.exports = {
    REQUIRED_FEILD_MISSING: 'REQUIRED_FEILD_MISSING',
    INVALID_FORMAT: 'INVALID_FORMAT',
    TYPE_MISMATCH: 'TYPE_MISMATCH',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DB_UNAVAILABLE: 'DB_UNAVAILABLE'
}
